name: manual

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/auth-actions@v1
        with:
          organization: testagents
          requested-token-type: urn:pulumi:token-type:access_token:organization
      - run: |
          curl -fsSL https://get.pulumi.com/esc/install.sh | sh
      - run: /home/runner/.pulumi/bin/esc env open testagents/test --format dotenv >> $GITHUB_ENV
      - run: echo ${{env.EXAMPLE_SETTING}}
