name: manual

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  fetch_secret:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    concurrency:
      group: ${{ matrix.run }}
      cancel-in-progress: false
    steps:
      - run: echo ${{matrix.run}}
      - uses: actions/checkout@v4
      - uses: pulumi/auth-actions@v1
        with:
          organization: testagents
          requested-token-type: urn:pulumi:token-type:access_token:organization
      - run: |
          curl -fsSL https://get.pulumi.com/esc/install.sh | sh
      - run: /home/runner/.pulumi/bin/esc env open testagents/test --format dotenv >> $GITHUB_ENV
      - run: echo ${{env.EXAMPLE_SETTING}}
