name: Pulumi pr
on:
  push:
jobs:
  up:
    name: Pulumi pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: test/dev
          cloud-url: https://501a-181-165-133-47.ngrok-free.app
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
