name: Update production PR gate

on:
  push:
    branches:
      - staging
  workflow_call:

permissions:
  pull-requests: write
  statuses: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-production-pr-gate:
    name: Update production PR gate
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find open production PR
        run: |
          PROD_POTENTIAL_MERGE_COMMIT=$(gh pr list -B production -s open --json commits -q ".|first.commits|last.oid")
          echo "PROD_POTENTIAL_MERGE_COMMIT=$PROD_POTENTIAL_MERGE_COMMIT" >> $GITHUB_ENV
      - name: Push commit state
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ env.PROD_POTENTIAL_MERGE_COMMIT }} \
            -f state='success' \
            -f target_url="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" \
            -f description="${{github.event.head_commit.message}}" \
            -f context="Staging release PR merged"
