name: TEST

on:
  push:
    branches:
      - staging
      - production

permissions:
  pull-requests: write
  statuses: write

jobs:
  update-production-pr-gate:
    name: Update production PR gate
    if: ${{ github.ref_name == 'staging' }}
    uses: ./.github/workflows/production-pr-gate-update.yml
    secrets: inherit

