name: TEST

on:
  push:
    branches:
      - staging
      - production

permissions:
  pull-requests: write
  statuses: write
  contents: read

jobs:
  update-production-pr-gate:
    name: Update production PR gate
    if: ${{ github.ref_name == 'staging' }}
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout service repository
        uses: actions/checkout@v4
      - name: Update production PR gate
        uses: ./.github/actions/production-pr-gate-update
        with:
          context: "Staging release PR merged"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

